language: python
python:
  - "2.7"
env:
  - DJANGO=1.6
  - DJANGO=1.6.8
  - DJANGO=1.7
  - DJANGO=1.7.1
install:
  - pip install -q Django==$DJANGO
before_script:
  - pwd
script:
  - python followit/tests/runtests.py
